spring:
  application:
    name: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/paytest?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B9
    username: root
    password:

  redis:
    host: 127.0.0.1
    port: 6379

  cache:
    type: redis
    cache-names: user

  mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8

logging:
  level:
    org.example: INFO
  file:
    name: /var/logs/myapp.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'

cache:
  ttl: '{"user":60,"dept":30}'